# Generated by Django 6.1.1 on 2026-09-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('query', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('display_name', models.TextField(blank=True, default='')),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'geocoding cache entry',
                'verbose_name_plural': 'geocoding cache entries',
            },
        ),
    ]
